@host = http://localhost:5250

### POST
POST {{host}}/api/pcs
Content-Type: application/json

{
  "name": "Student Laptop",
  "weight": 2.1,
  "warranty": 24,
  "createdAt": "2026-05-25T18:00:00",
  "stock": 7
}

###

### PUT
PUT {{host}}/api/pcs/4
Content-Type: application/json

{
  "name": "Updated Student Laptop",
  "weight": 2.3,
  "warranty": 36,
  "createdAt": "2026-05-25T18:00:00",
  "stock": 10
}

###

### DELETE
DELETE {{host}}/api/pcs/4

###

### 404 TEST
GET {{host}}/api/pcs/999/components